kind: Deployment
apiVersion: apps/v1
metadata:
  name: app2-deployment
  labels:
    app: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: s900274/k8s-demo-server
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: app2-config